---
# Ensure symlinks target paths is absent
- name: ANSISTRANO | Ensure shared paths targets are absent
  file: state=absent path={{ ansistrano_release_path.stdout }}/{{ item }}
  with_items: ansistrano_shared_paths

- name: ANSISTRANO | Ensure shared paths sources are present
  file: state=directory path={{ ansistrano_shared_path.stdout }}/{{ item }} mode="u=rwX,g=rwX,o=" recurse=yes owner={{ ansistrano_owner }} group={{ ansistrano_group }}
  with_items: ansistrano_shared_paths

# Symlinks shared paths
- name: ANSISTRANO | Create softlinks for shared paths
  file: state=link path={{ ansistrano_release_path.stdout }}/{{ item }} src={{ ansistrano_shared_path.stdout }}/{{ item }}
  with_items: ansistrano_shared_paths
